[build-system]
requires = ["setuptools>=65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyprismcast"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "hypercorn>=0.18.0",
    "pychromecast>=14.0.10",
    "quart>=0.21.0",
]

[project.scripts]
prismcast = "pyprismcast.main:main"

[tool.setuptools.packages.find]
where = ["."]
